import ExternSpecs.FluxCoreOption00.Flux.VC.TestReplaceReturnMatchesOriginal
import ExternSpecs.FluxCoreOption00.User.Proof.TestReplaceReturnMatchesOriginalProof

#check (F.TestReplaceReturnMatchesOriginal_proof : F.TestReplaceReturnMatchesOriginal)
