[package]
name = "flux-attrs"
version = "0.1.0"

edition.workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }

[features]
enabled = []

[lints]
workspace = true
