[package]
name = "flux-config"
version = "0.1.0"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.15.9", features = ["toml"], default-features = false }
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
