[package]
edition = "2021"
name = "flux-attrs-proc-macros-build"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.flux-attrs-proc-macros]
features = ["enabled"]
path = "../flux-attrs-proc-macros"
