[package]
edition = "2021"
name = "flux-config"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.12"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
