name = "lean_bench_all"
version = "0.1.0"
defaultTargets = ["LeanBenchAll"]

[[lean_lib]]
name = "LeanBenchAll"
roots = ["AllProofs"]
globs = [
  "AllProofs",
  "AbstractRefinements.**",
  "Array.**",
  "BuiltinAssocRefts.**",
  "Casts.**",
  "ConstGenerics.**",
  "Constructors.**",
  "Detached.**",
  "Enums.**",
  "ExternSpecs.**",
  "FnPtrs.**",
  "FoldUnfold.**",
  "ImplTrait.**",
  "Lifetimes.**",
  "OpaqueSorts.**",
  "RefinedAssocType.**",
  "Structs.**",
  "Surface.**",
  "TraitObject.**",
  "UserQualifiers.**",
  "Vec.**",
]

[[require]]
name = "LeanFixpoint"
path = "/Users/petros/Documents/UCSD/Work/lean-fixpoint"
