[package]
name = "flux-errors"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
